### ISSUE TITLE
"WebSocket is already in CLOSING or CLOSED state." doesn't resolve nor reject.

### ISSUE THREAD

**Issue by aifirst** [GetScatter/scatter-js#69]
I'm using chrome browser(for dapp) and Scatter desktop 9.6.1

When running dapp, I closed Scatter desktop.
-------------------------------------------------------------------------------------
	scatter.getIdentity(requiredFields).then(function()
	{
        ========= Resolve processing ============
	})
	.catch(function(err)
	{
        ========= Error prcoessing ==============
	});
---------------------------------------------------------------------
And when I call scatter.getIdentity, "WebSocket is already in CLOSING or CLOSED state." occurs.
But, it doesn't resolve nor reject.(neighter processing code is processed) so, I cannot process that error.

It is not exception. so, try ~ catch is useless.

I attached file which contains js files I'm using.

[js.zip](https://github.com/GetScatter/scatter-js/files/2642111/js.zip)

**Comment by nsjames** [comment]
This is an error thrown from the browser when it had a previous websocket connection to Scatter desktop, but scatter desktop was reloaded and the handshake is no longer valid. 

Usually you can just reload the page after reloading Scatter Desktop and it should solve it.

**Comment by aifirst** [comment]
Of course, if scater desktop is reopened and refresh web page, no problem. 
I want to notify to user, "Currently connection with scatter desktop was lost. please open scatter desktop and press F5". 
But this time, I cannot. I don't know if connection with scatter desktop is valid.

**Comment by dbendt** [comment]
This issue is occurring for me every time using latest Scatter Desktop and Scatter JS libraries. The initial authentication works, but any subsequent attempts are met with this error. Reloading Scatter and refreshing the page does not resolve the issue. Unable to find documentation of events.

**Comment by JackDiSalvatore** [comment]
I am having a similar issue, first connection and login works, but when logging out and attempting to log back in I receive the "Websocket is already in CLOSING or CLOSED state" error.

This did not happen when I was using
    "scatterjs-core": "^2.7.7",
    "scatterjs-plugin-eosjs": "^1.5.0"
    "eosjs": "^16.0.9",

but after upgrading to 
    "@scatterjs/core": "^2.7.47",
    "@scatterjs/eosjs2": "^1.5.29",
    "eosjs": "20.0.0",

it started happening.  I am looking through my app code to see if anything changed that I am not aware of.
